
package fi.jyu.it.ties456.week38.services.course;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CourseIS", targetNamespace = "http://week38.ties456.jyu.fi/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CourseIS {


    /**
     * 
     * @param teacherID
     * @param numberOfCredits
     * @param name
     * @param description
     * @return
     *     returns java.lang.String
     * @throws NoSuchTeacherException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createCourse", targetNamespace = "http://week38.ties456.jyu.fi/", className = "fi.jyu.it.ties456.week38.services.course.CreateCourse")
    @ResponseWrapper(localName = "createCourseResponse", targetNamespace = "http://week38.ties456.jyu.fi/", className = "fi.jyu.it.ties456.week38.services.course.CreateCourseResponse")
    public String createCourse(
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "teacherID", targetNamespace = "")
        String teacherID,
        @WebParam(name = "numberOfCredits", targetNamespace = "")
        int numberOfCredits,
        @WebParam(name = "description", targetNamespace = "")
        String description)
        throws NoSuchTeacherException_Exception
    ;

}
