
package fi.jyu.it.ties456.week38.services.course;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CourseISService", targetNamespace = "http://week38.ties456.jyu.fi/", wsdlLocation = "http://ub1.ad.jyu.fi/course?wsdl")
public class CourseISService
    extends Service
{

    private final static URL COURSEISSERVICE_WSDL_LOCATION;
    private final static WebServiceException COURSEISSERVICE_EXCEPTION;
    private final static QName COURSEISSERVICE_QNAME = new QName("http://week38.ties456.jyu.fi/", "CourseISService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://ub1.ad.jyu.fi/course?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COURSEISSERVICE_WSDL_LOCATION = url;
        COURSEISSERVICE_EXCEPTION = e;
    }

    public CourseISService() {
        super(__getWsdlLocation(), COURSEISSERVICE_QNAME);
    }

    public CourseISService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COURSEISSERVICE_QNAME, features);
    }

    public CourseISService(URL wsdlLocation) {
        super(wsdlLocation, COURSEISSERVICE_QNAME);
    }

    public CourseISService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COURSEISSERVICE_QNAME, features);
    }

    public CourseISService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CourseISService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CourseIS
     */
    @WebEndpoint(name = "CourseISPort")
    public CourseIS getCourseISPort() {
        return super.getPort(new QName("http://week38.ties456.jyu.fi/", "CourseISPort"), CourseIS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CourseIS
     */
    @WebEndpoint(name = "CourseISPort")
    public CourseIS getCourseISPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://week38.ties456.jyu.fi/", "CourseISPort"), CourseIS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COURSEISSERVICE_EXCEPTION!= null) {
            throw COURSEISSERVICE_EXCEPTION;
        }
        return COURSEISSERVICE_WSDL_LOCATION;
    }

}
