
package fi.jyu.it.ties456.week38.services.course;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "NoSuchTeacherException", targetNamespace = "http://week38.ties456.jyu.fi/")
public class NoSuchTeacherException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NoSuchTeacherException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public NoSuchTeacherException_Exception(String message, NoSuchTeacherException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public NoSuchTeacherException_Exception(String message, NoSuchTeacherException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: fi.jyu.it.ties456.week38.services.course.NoSuchTeacherException
     */
    public NoSuchTeacherException getFaultInfo() {
        return faultInfo;
    }

}
